### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by trinitysege** [AAROC/hackfest-warmups#5]
whenever i enter

`ssh oyeyiola@sgw-dev.sci-gaia.eu`

i get permission denied. I later find out that i have difference key therefore i try this command

`cat id_dsa.pub`

on git bash and i get these keys 

```
ssh-dss AAAAB3NzaC1kc3MAAACBALWCAkANYW81lOln2TC/Q9pmbZek6eM/bxXeFNAV9jdijHQmTpgNfKbf+W960Bc00Jh2wFuay2AjKWioGiVWVSxqdbgnyeS23KOvHnkfs9QA1Vr/Q90O0Cs7MDRalQOPu0s+9FGau0ieDroiuwGgUbOlAw5cO+TLj2DplIY8g5m7AAAAFQC3ds6fam95OVpPunkdjN2gER0aIQAAAIBrtg7m6MrW3C/Rleiv5I4DV8WvMToNJdZVS2IwM5h/J3MECoBWR5hrwdDhEoWXY7ImioFb1d1eItGkwy0DCHLNldCmCiCMj81t0brij0hbiorQwkLU77l/84U3zB3xIcpMtLoaG6t3/let7QzxCpVgXkgibk1VNqHw70UcqrEpwQAAAIEAowU10g/o+KjtEy/FaHaYarPuduw/9rMrVWbjWNNQF+uxXnk7qFPRpzS8WDUh4mIdsm/IemSbBFB5DWf3WJzzgkdqRFlCLGtvSQWSiGfYyXFmPL+sjwOANE8nJKK6HgTvpahxlvZsnWQtz7mcNIqDZWuTLqOTQf01bpgFAK8SMus= loveth@OYEYIOLA
```

 Although; i have copy these key into my github account and detected the one i met there but an error massage of Permission denied (publickey) still appear whenever i enter the command 
`ssh oyeyiola@sgw-dev.sci-gaia.eu`

**Comment by brucellino** [comment]
Thanks @trinitysege I think the issue may be with your username. I had set your username as`oyeyiola`, but your github user name is actually trinitysege. I'm updating the playbook now and will re-run the configuration. I'll let you know when you can try again.

**Comment by brucellino** [comment]
Ok, the changed has been picked up : 

```
hanged: [sgw-dev.sci-gaia.eu] => (item={u'github': {u'username': u'trinitysege', u'confirmed': True}, u'name': u'Segun oyeyiola', u'institute': u'Obafemi Awolowo University, Ife.', u'twitter': None, u'orcid': None, u'homepage': None, u'email': u'trinitysege@gmail.com'})
```
Can you try to log in again please.

**Comment by trinitysege** [comment]
When I used ssh trinitysege@sgw-dev.sci-gaia.eu it work now; thanks.

If I have any other problem, which i don't hope for, I will let you know.

Regard.
