### ISSUE TITLE
Unable to add collections to gLibrary repos

### ISSUE THREAD

**Issue by cudanor** [AAROC/hackfest-warmups#6]
curl -H "Authorization: $TOKEN" 
https://glibrary.ct.infn.it:3500/v2/repos/plantisc2/

returns error 401 - Authorization required.

**Comment by brucellino** [comment]
Hi @cudanor - it looks like you are missing a verb - GET or POST is required. I'm assuming you're trying to  list the entries, since there's no data being sent (`-d {}`).

However, the 401 message probably means that your token is incorrect. does `echo $TOKEN` give you a valid token ?

**Comment by cudanor** [comment]
Yes, my token expired.
Solved
